export const UserData = [
  {
    id: 1,
    role: "admin",
    status: "Teacher",
    username: "user1",
    password: "admin123",
    name: "Ricky Fernando",
    jabatan: "Kepala Sekolah",
    avatar: "/gambar/babi.jpg"
  },
  {
    id: 2,
    role: "user",
    status: "Teacher",
    username: "user2",
    password: "123",
    name: "Thiago",
    jabatan: "Wakil Kepala Sekolah",
    avatar: "/gambar/anjing1.jpg"
  },
  {
    id: 3,
    role: "user",
    status: "Student",
    username: "user3",
    password: "admin123",
    name: "Eyline",
    jabatan: "XI IPA",
    avatar: "dog-3.jpg"
  },
  {
    id: 4,
    role: "admin",
    status: "Staff",
    username: "user4",
    password: "admin123",
    name: "Cherline",
    jabatan: "Kepala Tata Usaha",
    avatar: "/gambar/kucing.png",
  },
  {
    id: 5,
    role: "user",
    status: "Teacher",
    username: "user5",
    password: "admin123",
    name: "Anna Müller",
    jabatan: "Wakil Kepala Sekolah",
    avatar: "/gambar/dog2.jpg",
  },
  {
    id: 6,
    role: "user",
    status: "Teacher",
    username: "user6",
    password: "admin123",
    name: "Luca Rossi",
    jabatan: "Kepala Kurikulum",
    avatar: "bg-orange-600",
  },
  {
    id: 7,
    role: "user",
    status: "Teacher",
    username: "user7",
    password: "admin123",
    name: "Sophie Dubois",
    jabatan: "Kepala Kesiswaan",
    avatar: "bg-yellow-600",
  },
  {
    id: 8,
    role: "user",
    status: "Teacher",
    username: "user8",
    password: "admin123",
    name: "Peter Johansson",
    jabatan: "Kepala Sarana & Prasarana",
    avatar: "bg-purple-600",
  },
  {
    id: 9,
    role: "user",
    status: "Teacher",
    username: "user9",
    password: "admin123",
    name: "Elena Novak",
    jabatan: "Kepala Perpustakaan",
    gambar: "bg-green-600"
  },
  {
    id: 10,
    role: "user",
    status: "Student",
    username: "user10",
    password: "admin123",
    name: "Lucas Schneider",
    jabatan: "X IPA 1",
  },
  {
    id: 11,
    role: "user",
    status: "Student",
    username: "user11",
    password: "admin123",
    name: "Noah Andersen",
    jabatan: "X IPA 1",
  },
  {
    id: 12,
    role: "user",
    status: "Student",
    username: "user12",
    password: "admin123",
    name: "Emma Fischer",
    jabatan: "X IPS 2",
  },
  {
    id: 13,
    role: "user",
    status: "Student",
    username: "user13",
    password: "admin123",
    name: "Noah Andersen",
    jabatan: "XI IPA 1",
  },
  {
    id: 14,
    role: "user",
    status: "Student",
    username: "user14",
    password: "admin123",
    name: "Clara Moretti",
    jabatan: "XI Bahasa",
  },
]